spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yuproject?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: alsrb!0119
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

